# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

es:
  home: Inicio
  about: Acerca de
  services: Servicios
  team: Equipo
  portfolio: Portafolio
  contact: Contacto
  view: English

  titles:
    about: Acerca de Twins VR Renovation Inc 
    services: Servicios
    team: Equipo
    portfolio: Portafolio de servicios
    contact: Contactanos
  twins_vr_r: Twins VR Renovation Inc
  toggle_nav: Toggle navigation
  renovation: RenovationInc
  twinsvr: TwinsVR
  welcome: BIENVENIDO  
  learn_more: Sobre nosotros
  title1: CONFIABILIDAD
  expe: Contamos con mas de 10 años de experiencia en el terreno laboral de la reconstrucción
  title2: INNOVACIÓN 
  stereotype: Escapamos del estereotipo de constructura
  vision: VISIÓN
  intro: > 
    Somos una empresa innovadora especializada en remodelacion de hoteles, contamos con un equipo de trabajo profesional
    y con experiencia, que provee el mejor servicio basado en sus conocimientos.
  intro2: Ofrecemos un producto de la mas alta calidad a un precio accesible y trabajamos basados en sus necesidades.
  intro3: >
    El fundador y controlador de operaciones de la empresa cuenta con mas de 10 años de experiencia en el terreno laboral
    de la reconstruccion en todas las areas. El rapido desarrollo de la empresa depende de la experiencia y capacidad de su equipo, 
    asi como su desempeño y rapidez en produccion, con un sistema de gestion totalmente orientado al cliente, y perfilada
    con unos valores presentes en todas nuestras actuaciones: transparencia, seriedad y compromiso.
  vision1: >
    En Twins VR Renovation Inc. escapamos del estereotipo de constructura, del discurso estandar y del conformismo
    de ser uno mas en el directorio de empresa. Queremos distinguirnos, salirnos de la fila, ofrecer un valor añadido
    que deje nuestra impronta en los proyectos que ejecutamos, permaneciendo siempre atentos a la nuevas tendencias y
    dispuestos a dar respuesta a las exigencias de nuestros clientes.
  vision2: >
    Afrontamos el día a día con el objetivo de posicionarnos como empresa referente en el sector, de marcar un camino
    y una metodología de trabajo que nos distingan en el mercado como su constructura de confianza.
  service1: Paneles de yeso
  service2: Textura de techo y pared
  service3: Vinilo
  service4: Loseta y alfombra
  service5: Pintura
  service6: Carpintería
  service7: Pisos de madera
  service8: Muebles y accesorios
  service9: Remodelación de baño completo
  our_servic: Our Services
  expert_cod: Expert Coder
  creative_d: Creative Designer
  wordpress_: Wordpress Developer
  social_mar: Social Marketer 
  seo_expart: Seo Expart
  247_suppo: 24/7 Support
  web_design: Web Design
  graphics_d: Graphics Design
  php_develo: Php Developer
  java_scrip: Java Script
  faq_questi: Faq Question
  project: Project
  planning: Planning
  success: Success
  project: Project
  planning: Planning
  success: Success
  welcome_to: Welcome To Our eBusiness
  subscribe: Subscribe
  our_specia: Our special Team
  jhon_micke: Jhon Mickel
  seo: Seo
  andrew_arn: Andrew Arnold
  web_develo: Web Developer
  lellien_li: Lellien Linda
  web_design: Web Design
  jhon_powel: Jhon Powel
  seo_expert: Seo Expert
  working_wi: working with us
  web_design: Web Design, Ready Home, Construction and Co-operate Outstanding Buildings.
  contact_us: Contact us
  all: All
  developmen: Development
  design: Design
  photoshop: Photoshop
  business_c: Business City
  web_develo: Web Development
  blue_sea: Blue Sea
  photosho: Photosho
  beautiful_: Beautiful Nature
  web_design: Web Design
  creative_t: Creative Team
  web_design: Web design
  beautiful_: Beautiful Flower
  web_develo: Web Development
  night_hill: Night Hill
  photoshop: Photoshop
  pricing_ta: Pricing Table
  basic: basic
  online_sys: Online system
  full_acces: Full access
  free_apps: Free apps
  multiple_s: Multiple slider
  free_domin: Free domin
  support_un: Support unlimited
  payment_on: Payment online
  cash_back: Cash back
  sign_up_no: sign up now
  top_sale: top sale
  standar: standar
  online_sys: Online system
  full_acces: Full access
  free_apps: Free apps
  multiple_s: Multiple slider
  free_domin: Free domin
  support_un: Support unlimited
  payment_on: Payment online
  cash_back: Cash back
  sign_up_no: sign up now
  premium: premium
  online_sys: Online system
  full_acces: Full access
  free_apps: Free apps
  multiple_s: Multiple slider
  free_domin: Free domin
  support_un: Support unlimited
  payment_on: Payment online
  cash_back: Cash back
  sign_up_no: sign up now
  boby: Boby
  jhon: Jhon
  fleming: Fleming
  latest_new: Latest News
  13_comment: 13 comments
  assumenda_: Assumenda repud eum veniam
  read_more: Read more
  130_commen: 130 comments
  explicabo_: Explicabo magnam quibusdam.
  read_more: Read more
  10_comment: 10 comments
  lorem_ipsu: Lorem ipsum dolor sit amet
  read_more: Read more
  welcome_to: Welcome to our eBusiness company
  get_a_quat: Get A quate
  contact_us: Contact us
  monday-fri: Monday-Friday (9am-5pm)
  web_www_e: "Web: www.example.com"
  ny_535022,: NY 535022, USA
  your_messa: Your message has been sent. Thank you!
  send_messa: Send Message
  business: Business
  sed_ut_per: Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.
  informatio: information
  phone: +123 456 789
  contact@ex: contact@example.com
  9am-5pm: 9am-5pm
  instagram: Instagram
  ebusiness: eBusiness
  bootstrapm: BootstrapMade


en:
  home: Home
  about: About
  services: Services
  team: Team
  portfolio: Portfolio
  contact: Contact
  view: Español

  titles:
    about: About Twins VR Renovation Inc
    services: Our Services
    team: Our special Team
    portfolio: Portfolio of worksss
    contact: Contact Us
  twins_vr_r: Twins VR Renovation Inc
  toggle_nav: Toggle navigation
  renovation: RenovationInc
  twinsvr: TwinsVR
  welcome: WELCOME 
  see_servic: See Services
  learn_more: Learn More
  title1: RELIABILITY
  title2: INNOVATION
  stereotype: We escape the construction stereotype
  expe: We have more than 10 years of experience in the reconstruction work field
  intro: >
    We are an innovative company specialized in hotel remodeling, we have a professional
    and experienced team that provides the best service based on their knowledge.
  intro2: We offer a product of the highest quality at an affordable price and work based on your needs.
  intro3: >
    The founder and operations controller of the company has more than 10 years of experience in the
    reconstruction work field in all areas. The rapid development of the company depends on the experience
    and capacity of its team, as well as its performance and speed in production, with a management system totally
    oriented to the client, and outlined with values present in all our actions: transparency, seriousness and commitment.
  vision: VISION
  vision1: >
    In Twins VR Renovation Inc. we escape the stereotype of the structure, the standard discourse and the conformism
    of being one more in the company directory. We want to distinguish ourselves, get out of line, offer an added value 
    that leaves our mark on the projects we execute, always remaining attentive to new trends and willing to respond to
    the demands of our customers.
  vision2: >
    We face every day with the aim of positioning ourselves as a leading company in the sector,
    of marking a path and a work methodology that distinguish us in the market as its trust structure.
  our_servic: Our Services
  service1: Plasterboard
  service2: Ceiling and wall texture
  service3: Vinyl
  service4: Tile and carpet
  service5: Paint
  service6: Carpentry
  service7: Wood floors
  service8: Furniture and accessories
  service9: Complete bathroom remodeling
  expert_cod: Expert Coder
  creative_d: Creative Designer
  wordpress_: Wordpress Developer
  social_mar: Social Marketer 
  seo_expart: Seo Expart
  247_suppo: 24/7 Support
  web_design: Web Design
  graphics_d: Graphics Design
  php_develo: Php Developer
  java_scrip: Java Script
  faq_questi: Faq Question
  project: Project
  planning: Planning
  success: Success
  project: Project
  planning: Planning
  success: Success
  welcome_to: Welcome To Our eBusiness
  subscribe: Subscribe
  our_specia: Our special Team
  jhon_micke: Jhon Mickel
  seo: Seo
  andrew_arn: Andrew Arnold
  web_develo: Web Developer
  lellien_li: Lellien Linda
  web_design: Web Design
  jhon_powel: Jhon Powel
  seo_expert: Seo Expert
  working_wi: working with us
  web_design: Web Design, Ready Home, Construction and Co-operate Outstanding Buildings.
  contact_us: Contact us
  all: All
  developmen: Development
  design: Design
  photoshop: Photoshop
  business_c: Business City
  web_develo: Web Development
  blue_sea: Blue Sea
  photosho: Photosho
  beautiful_: Beautiful Nature
  web_design: Web Design
  creative_t: Creative Team
  web_design: Web design
  beautiful_: Beautiful Flower
  web_develo: Web Development
  night_hill: Night Hill
  photoshop: Photoshop
  pricing_ta: Pricing Table
  basic: basic
  online_sys: Online system
  full_acces: Full access
  free_apps: Free apps
  multiple_s: Multiple slider
  free_domin: Free domin
  support_un: Support unlimited
  payment_on: Payment online
  cash_back: Cash back
  sign_up_no: sign up now
  top_sale: top sale
  standar: standar
  online_sys: Online system
  full_acces: Full access
  free_apps: Free apps
  multiple_s: Multiple slider
  free_domin: Free domin
  support_un: Support unlimited
  payment_on: Payment online
  cash_back: Cash back
  sign_up_no: sign up now
  premium: premium
  online_sys: Online system
  full_acces: Full access
  free_apps: Free apps
  multiple_s: Multiple slider
  free_domin: Free domin
  support_un: Support unlimited
  payment_on: Payment online
  cash_back: Cash back
  sign_up_no: sign up now
  boby: Boby
  jhon: Jhon
  fleming: Fleming
  latest_new: Latest News
  13_comment: 13 comments
  assumenda_: Assumenda repud eum veniam
  read_more: Read more
  130_commen: 130 comments
  explicabo_: Explicabo magnam quibusdam.
  read_more: Read more
  10_comment: 10 comments
  lorem_ipsu: Lorem ipsum dolor sit amet
  read_more: Read more
  welcome_to: Welcome to our eBusiness company
  get_a_quat: Get A quate
  contact_us: Contact us
  monday-fri: Monday-Friday (9am-5pm)
  web_www_e: "Web: www.example.com"
  ny_535022,: NY 535022, USA
  your_messa: Your message has been sent. Thank you!
  send_messa: Send Message
  business: Business
  sed_ut_per: Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.
  informatio: information
  phone: +123 456 789
  contact@ex: contact@example.com
  9am-5pm: 9am-5pm
  instagram: Instagram
  ebusiness: eBusiness
  bootstrapm: BootstrapMade